### ISSUE TITLE
loging in for the first time

### ISSUE THREAD

**Issue by aqueiroz** [theirc/CTS#34]
hi guys, i finally managed to get the dev environment working... took me 2 days, had lots of issues.

now at the last hurdle...

how do i login for the first time?
how can i setup a admin user? or is there a default one?

thank you in advance

andre

**Comment by vkurup** [comment]
Hi,

Yes, the documentation makes a lot of assumptions about Django knowledge. A superuser can be created with this command: https://docs.djangoproject.com/en/1.8/intro/tutorial02/#creating-an-admin-user

If you are setting this up locally, do this in the main project directory:

```
$ workon cts
(cts)$ python manage.py createsuperuser
```

... and then follow the prompts. You should then be able to login via the web interface with those credentials.

**Comment by aqueiroz** [comment]
Awesome. Thank you so much.... will try tomorrow.

Yeah django was fun but had a few issues. Am more of a Lamp user... but
still managed to get it working.

Once again thank you

Regards

Andre

**Comment by vkurup** [comment]
Great. If there are specific stumbling blocks in the documentation that can be improved, please let us know. I'll close this issue now, but please let us know if you have further issues. Good luck!

**Comment by aqueiroz** [comment]
I will look it over again... and make a few notes. Then send it over to you.

Regards

Andre

**Comment by aqueiroz** [comment]
Hi Vinod

ok managed to login. seems to be working nicely...
Now what, this is where the documentation stops.

I did manage to set up my android phone with ODK and it sends data to my
https://ona.rescue.org/aqueiroz/.

Im assuming i need to tell Django somewhere to go to the
https://ona.rescue.org/aqueiroz/ and pull the data.? or am i wrong?

Also where do QR codes come in?

Lets say I have a whole list of items to be shipped. i convert each item
details into a QR code... i attach this codes to be box and scan it. the
details get submitted to Ona. is that how it works?

Sorry about all the questions... i do think this is a great open source
project.

Thank you for the help.

Regards

Andre

On 5 February 2016 at 20:55, Andre Queiroz andy1979s@gmail.com wrote:

> I will look it over again... and make a few notes. Then send it over to
> you.
> 
> Regards
> 
> Andre
> On 5 Feb 2016 20:22, "Vinod Kurup" notifications@github.com wrote:
> 
> > Closed #34 https://github.com/theirc/CTS/issues/34.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/theirc/CTS/issues/34#event-541166441.

## 

Dre

Http://www.brazilartsandcrafts.com
http://www.brazilianchef.co.uk/ http://www.foodiefanatic.co.uk/

**Comment by watsonj** [comment]
Hi Andre —
Correct on all fronts. You need to point to the form on Ona for CTS to poll and pull the data.

The QR codes that CTS generates get scanned into ODK Collect using a QR Code scanner and then matched in the DB. 

Not the most sophisticated of apps, but we were under duress to produce something quickly, and … well here it is. Caktus did a great job migrated the code from PHP to Django/Python. And doing the documentation.

**Comment by aqueiroz** [comment]
Thanks for the reply Jake...
So where in my test CTS do I point to on a.  Or is there a configuration
doc that I haven't seen?

Also when do the qr codes get generated? I created some test kits, packages
and shipments but haven't seen a qr yet...

I think the solution is great. Does not need to be sophisticated if it
works.

Great work guys.

Just need to make the documentation better for us less skilled IT folk ☺.

Thank you so much for the help

Regards

Andre
